#!/usr/bin/env bash

set -e

gemfury_push_token="$1"
package_version=$(grep '__version__ =' faust/__init__.py | awk '{print $3}' | tr -d "'")


# create dist using python setup dist
python3 setup.py sdist
# push dist to gemfury using curl and token
curl -F package=@dist/faust-$package_version.tar.gz https://$gemfury_push_token@push.fury.io/themuse
